# Generated by Django 3.1.7 on 2021-03-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='input_date',
            field=models.DateField(null=True),
        ),
    ]
